version: "3.8"
services:
  web-app:
    image: "docker.pkg.github.com/istyebisu/web-app/web-app:latest"
    ports:
      - "4200:80"
    networks:
      - shared-net
  configuration-server:
    image: "docker.pkg.github.com/istyebisu/configuration-server/configuration-server:latest"
    ports:
      - "8081:8080"
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - shared-net
  medusa-proxy:
    image: "docker.pkg.github.com/istyebisu/medusa-proxy/medusa-proxy:latest"
    ports:
      - "8082:8080"
    networks:
      - shared-net
  mongo:
    image: 'mongo'
    ports:
      - 27017:27017
    container_name: mongo
    networks:
      - shared-net
networks:
  shared-net:
    driver: bridge
